name: Unit Testing

on:
  pull_request:
  push:

jobs:
  solidity:
    name: "Solidity Testing (Max Proposals = ${{ matrix.max-proposals }})"
    strategy:
      matrix:
        max-proposals: [3, 4, 5]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository
      - uses: actions/setup-node@v2
        name: Setup nodejs
        with:
          node-version: 14
      - run: npm i -g yarn@latest
        name: Upgrade yarn
      - run: yarn global add truffle
        name: Install truffle
      - run: yarn test:sol
        name: Perform unit test 
        env:
          MAX_PROPOSALS: ${{ matrix.max-proposals }}
      
